---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.6.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Practical Statistics for Data scientists

<https://github.com/gedeck/practical-statistics-for-data-scientists>

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import trim_mean
import seaborn as sns

print("Hello notebook")
```

## Exploring two or more variables

### Hexagonal binning and contours (plotting numeric vs. numeric data)

Sample dataset: `kc_tax`

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
kc_tax = pd.read_csv('data/kc_tax.csv.gz')
kc_tax.head()
```

In order to focus on the main part of the data, we strip out very expensive and very small or large residences.
In pandas, `Dataframe.loc` allows access of a group of rows and columns by label(s) or a boolean array.

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
kc_tax0 = kc_tax.loc[(kc_tax.TaxAssessedValue < 750000) & (kc_tax.SqFtTotLiving > 100) & (kc_tax.SqFtTotLiving < 3500), :]
#kc_tax0 = kc_tax.loc[(kc_tax.TaxAssessedValue < 750000), :]
print(kc_tax0.shape) # (432693, 3)
kc_tax0.head()
```

Rather than plotting points, which would appear as a monolithic dark cloud, we group the records into
hexagonal bins and plotted the hexagons with a color indicating the number of records in that bin (**hexagonal plot**).

Scatterplot vs. hexagonal plot.

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
# the following provides no hint
kc_tax0.plot.scatter(x='SqFtTotLiving', y='TaxAssessedValue')

# the following shows the positive relationship between square feet and tax-assessed value
kc_tax0.plot.hexbin(x='SqFtTotLiving', y='TaxAssessedValue', gridsize=30, sharex=False)
```

Contour plot using seaborn's **`kdeplot`**

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
ax = kc_tax0.plot.scatter(x='SqFtTotLiving', y='TaxAssessedValue')
#ax = sns.kdeplot(kc_tax0.SqFtTotLiving, kc_tax0.TaxAssessedValue, ax=ax)
#ax.set_xlabel('Finished Square Feet')
#ax.set_ylabel('Tax-Assessed Value')
```

### Two categorical variables: contingency table ..

Example: `Lending Club`. 
Two columns: `grade` (A [high] to G [low]) 
and `status`  (fully paid, current, late, or charged off [loan balance not expected to be collected]). 
High-grade loans have a very low late/charge-off percentage as compared with lower-grade loans.

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
lc_loans = pd.read_csv('data/lc_loans.csv')
lc_loans.head()
```

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
# 'margins' keyword argument will add the column and row sums
crosstab = lc_loans.pivot_table(index='grade', columns='status', aggfunc=lambda x: len(x), margins=True)
crosstab
```

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
# We create a copy of the pivot table, ignoring the column sums.
df = crosstab.loc['A':'G',:].copy()
# We divide the rows with the row sum to get row-wise percentages: 
# i.e., the proportion of loans of a given status per a certain grade
df.loc[:,'Charged Off':'Late'] = df.loc[:,'Charged Off':'Late'].div(df['All'],
axis=0)
# We divide the 'All' column by its sum to get the percentage of grades
df['All'] = df['All'] / sum(df['All'])
perc_crosstab = df
perc_crosstab
```

<!-- #region pycharm={"name": "#%% md\n"} -->
## Numerical and categorical data

Example: **Airline Stats** - rows are flights with information about the `airline` company and different sources for delays 
(`pct_carried_delay` [airplane is late], `pct_atc_delay` [air traffic control system], `pct_weather_delay`).
<!-- #endregion -->

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
airline_stats = pd.read_csv('data/airline_stats.csv')
airline_stats.head()
```

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
ax = airline_stats.boxplot(by='airline', column='pct_carrier_delay')
ax.set_ylabel('Daily % of Delayed Flights')
#plt.suptitle('')
```

<!-- #region pycharm={"name": "#%% md\n"} -->
Violin plot
<!-- #endregion -->

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
# Get the categorical values of 'airline' variable (these will be used to set the order of categories in the violinplot)
airline_stats['airline'] = pd.Categorical(airline_stats['airline'])
airlines = list(airline_stats['airline'].cat.categories)

ax = sns.violinplot(airline_stats.airline, airline_stats.pct_carrier_delay,
inner='quartile', color='orange', order=airlines)
#ax.set_xlabel('')
ax.set_ylabel('Daily % of Delayed Flights')
```

<!-- #region pycharm={"name": "#%% md\n"} -->
### Visualising multiple variables through conditioning/facets

Let's consider the `kc_tax` dataset. We showd that a cluster of homes have hgiher tax-assessed value per square foot.
To get this clearer, we show the effect of location by plotting data  for a set of zip codes.
In particular, we show that tax-assessed value is
much higher in some zip codes (98105, 98126) than in others (98108, 98188).
<!-- #endregion -->

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
zip_codes = [98188, 98105, 98108, 98126]
kc_tax_zip = kc_tax0.loc[kc_tax0.ZipCode.isin(zip_codes),:]
kc_tax_zip.head()
```

```{python pycharm={'name': '#%%\n', 'is_executing': False}}
def hexbin(x, y, color, **kwargs):
  cmap = sns.light_palette(color, as_cmap=True)
  plt.hexbin(x, y, gridsize=25, cmap=cmap, **kwargs)

g = sns.FacetGrid(kc_tax_zip, col='ZipCode', col_wrap=2)
g.map(hexbin, 'SqFtTotLiving', 'TaxAssessedValue', extent=[0, 3500, 0, 700000])
g.set_axis_labels('Finished Square Feet', 'Tax-Assessed Value')
g.set_titles('Zip code {col_name:.0f}')
```
